version: "2"
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: false
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
    config:
      threshold: 128
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: false
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
    channel: "stable"
    checks:
      complexity:
        enabled: false
exclude_patterns:
- "**/test/"
- "**/bench/"
- "**/v0/"
- "**/node_modules/"
ratings:
  paths:
  - "index.js"
  - "objectSorter.js"
